version: "3"

services:
  app:
    image: autoref:latest
    build: .
    command: [ "gui" ]
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
